import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const className = "dark"
  return (
    <html lang="es">
      <body className={`${inter.className} dark text-foreground bg-background w-full h-full`}>
        <NextUIProvider locale="es" className={className}>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
